"$schema" = 'https://starship.rs/config-schema.json'
add_newline = true
command_timeout = 2000

[battery]
full_symbol = "ğŸ”‹"
charging_symbol = "ğŸ”Œ"
discharging_symbol = "âš¡"

[[battery.display]]
threshold = 30
style = "bold red"

[character]
error_symbol = "[â¯](bold red)"

[cmd_duration]
min_time = 10000  # Show command duration over 10,000 milliseconds (=10 sec)
format = "took [$duration]($style)"

[username]
style_user = "blue bold dimmed"
show_always = true

[directory]
truncation_length = 5
format = "[$path]($style)[$lock_symbol]($lock_style)"

# [hostname]
# ssh_only = false
# format = "<[$hostname]($style)>"
# trim_at = "-"
# style = "bold dimmed white"
# disabled = true

[package]
disabled = false

[git_branch]
format = "	[$symbol$branch]($style)	"

[git_commit]
commit_hash_length = 8
style = "bold white"

[git_state]
format = "[($state( $progress_current of $progress_total))]($style)"

[git_status]
conflicted = "âš”ï¸ "
ahead = "ğŸï¸ ğŸ’¨ Ã—${count}"
behind = "ğŸ¢ Ã—${count}"
diverged = "ğŸ”± ğŸï¸ ğŸ’¨ Ã—${ahead_count} ğŸ¢ Ã—${behind_count}"
untracked = "ğŸ›¤ï¸  Ã—${count}"
stashed = "ğŸ“¦ "
modified = "ğŸ“ Ã—${count}"
staged = "ğŸ—ƒï¸  Ã—{count}"
renamed = "ğŸ“› Ã—${count}"
deleted = "ğŸ—‘ï¸  Ã—{count}"
style = "bright-white"
format = "$all_status$ahead_behind"

# [memory_usage]
# format = "$symbol[${ram}( | ${swap})]($style)    "
# threshold = 70
# style = "bold dimmed white"
# disabled = true

# [time]
# time_format = "%T"
# format = "ğŸ•™ $time($style)	"
# style = "bright-white"
# disabled = true
